version: "3"

services:
  redis:
    container_name: redis
    hostname: redis
    image: icmdb/redis
    environment:
     - REDIS_DEBUG=
     - REDIS_DELAY=1
     - REDIS_PORT=6379
     - REDIS_REQUIREPASS=Passw0rd4Redis
     - REDIS_RENAME_COMMAND_CONFIG=renamedconfig
    expose:
     - 6379
    #ports:
    # - 6379:6379
    restart: always
    
  redis-manager:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: redis-manager
    hostname: redis-manager
    image: icmdb/redis-manager
    environment:
     - REDIS_HOST=redis
     - REDIS_PASSWORD=Pass0rd4Redis
     - REDIS_PORT=6379
    ports:
     - 8000:8000
     - 1087:1087
    links:
     - redis:redis
    restart: always
